### ISSUE TITLE
Cadence not displaying xruns properly

### ISSUE THREAD

**Issue by kflak** [falkTX/Cadence#259] opened 2019-11-15 12:06 UTC
Instead of xruns displaying the actual xruns count, I am now getting `dbus.UInt32(0)`. I'm not quite sure when this started, but I am running the latest `cadence-git` version from aur/Arch Linux and `community/jack2`. 
Kernel version: 5.2.21-rt13-1-rt

**Comment by falkTX** [comment] 2019-11-15 17:27
Likely some python-dbus change.
I cannot reproduce this in my system, patches/PR welcome

**Comment by deepsummersee** [comment] 2019-11-15 22:19
I'm also experiencing xrun display issues alongside not being able to change anything in the configuration menu--the setting simply reset upon closing, so I cannot select my device correctly.

**Comment by kflak** [comment] 2019-11-16 06:47
Seems the connection through dbus is indeed very problematic. I am getting this when pushing the `stop` button:
```
Traceback (most recent call last):
  File "/usr/share/cadence/src/cadence.py", line 1671, in slot_JackServerStop
    gDBus.a2j.stop()
  File "/usr/lib/python3.8/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3.8/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.gna.home.a2jmidid.error.generic: a2j_stop() failed.
```
`Start` and `Force restart` works as expected. 

Unfortunately my python skills are approximating zero, so I won't be able to patch anything...

**Comment by unfa** [comment] 2019-11-16 08:27
@deepsummersee What OS are you running?

Have you guys updated recently?

**Comment by deepsummersee** [comment] 2019-11-16 08:34
Arch Linux 64-bit kernel `5.3.11-arch1-1`
Yes, I received a boatload of python updates a couple of days ago.

**Comment by falkTX** [comment] 2019-11-17 19:43
Fixed in latest git, thanks @terencode for the PR!

Release coming soon. Either today or tomorrow

**Closed** 2019-11-17 19:43 UTC

**Comment by kflak** [comment] 2019-11-18 12:28
Thanks for the quick fix! I can confirm that it works now on my system.
